services:
  product-service:
    build:
      context: ./ProductService
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=ProductDb;User id=sa;Password=sqlserver;MultipleActiveResultSets=true;TrustServerCertificate=true;

  order-service:
    build:
      context: ./OrderService
    ports:
      - "8002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=OrderDb;User id=sa;Password=sqlserver;MultipleActiveResultSets=true;TrustServerCertificate=true;
